### PR TITLE
Add openblas binary for windows

### PR DESCRIPTION
**Pull request by jarrodmillman**
@rgommers I created a new scipy/scipy-ci repo and added the openblas binary for windows per https://github.com/scipy/scipy/issues/15854

I am happy to have this deleted or renamed, obviously. But if this seems reasonable, I can make a PR to update `.github/workflows/windows.yml`.

### CODE REVIEW

**Comment by rgommers** [comment]
This seems like a good idea to me, thanks @jarrodmillman. Cc also @matthew-brett.

Re the name, maybe good to make it a little more explicit, mostly to make it explicit that this is for some binaries/artifacts and not CI config/scripts. Naming stuff is hard, so let me throw out a few thoughts: `ci-artifacts`, `scipy-ci-artifacts`, `dev-ci-prebuilds`.

**Comment by tylerjereddy** [comment]
`ci-artifacts` seems "ok" to me; will there be a short description somewhere/`README` about how that special version of OpenBLAS was produced?

**Comment by jarrodmillman** [comment]
I slightly prefer `scipy-ci-artifacts`. I can imagine I may end up with `ci-artifacts` or something similar in a few GH orgs. But I don't have a strong preference.

**Comment by jarrodmillman** [comment]
> will there be a short description somewhere/`README` about how that special version of OpenBLAS was produced?

That seems like a good idea. But I would prefer merging this and  scipy/scipy#16118 sooner than later. Maybe I am alone, but I find having the CI regularly failing annoying and distracting.

**Comment by jarrodmillman** [comment]
I am going to merge this now, since it seems like the general idea is acceptable to everyone. We can rename the repo later, if desired.

**Pull request merged**
